# Scraping Financials From BOM - 1980-2020

In [1]:
import pandas as pd

# Create A List Of Years as Strings
years = str(list(range(1979, 2022)))
years = years.split(',')
years = [x.strip() for x in years]
years = years[1:42]

In [2]:
# Scraping and Appending The Tables On A Loop Using The Variable year as html identifier
import requests

appended_data = pd.DataFrame([])
for year in years:
    url = 'https://www.boxofficemojo.com/year/'+year+'/?grossesOption=calendarGrosses'
    html = requests.get(url).content
    # Creating The Dataframe and Adding The Year As Identifier Column Within Main Dataframe
    df_list = pd.read_html(html)
    dist_df = df_list[-1]
    dist_df['Release Year'] = year
    
    appended_data=appended_data.append(dist_df,ignore_index=True)
    appended_data.to_csv('1980_2020.csv', index=False)

In [3]:
# Loading The Dataframe From Newest To Oldest
df = pd.read_csv('1980_2020.csv')
df = df.sort_index(ascending=False)
df = df.drop('Estimated', axis=1)
df.head(2)

,Rank,Release,Genre,Budget,Running Time,Gross,Theaters,Total Gross,Release Date,Distributor,Release Year
19749,455,Love Goes Public,-,-,-,$38,-,"$5,738",Oct 25,Aspiration Entertainment,2020
19748,454,Benjamin the Elephant (2020),-,-,-,$49,1,$49,Oct 16,Viva Pictures,2020

# Scraping The Distributer Market Share From the-numbers.com

In [4]:
# Using PReloaded Modules Requests / Pandas
url = 'https://www.the-numbers.com/market/distributors'
html = requests.get(url).content
df_list = pd.read_html(html)
dist_df = df_list[-1]
dist_df.to_csv('distributors.csv', index=False)

In [6]:
# View Dataframe (NEED TO COMPARE TO  ADD ALT SPELLINGS E.G. Twentith Century & 20th Century)
dist_df = pd.read_csv('distributors.csv')
dist_df.head()

   Rank       Distributor  Movies Total Box Office     Tickets   Share
0     1       Walt Disney     580  $39,701,839,300  5667112915  16.92%
1     2      Warner Bros.     806  $35,685,559,812  5137108875  15.21%
2     3     Sony Pictures     734  $28,782,998,644  4257714689  12.27%
3     4         Universal     517  $27,514,431,021  3943038875  11.73%
4     5  20th Century Fox     522  $25,855,984,961  3792174776  11.02%

In [7]:
# Create A Dictionary From Two Columns of Distributors/Market Share Table To Map To df
distributors = dist_df['Distributor'].tolist()
market_share = dist_df['Share'].tolist()
dist_share_dict = dict(zip(distributors, market_share))

In [9]:
# Mapping The Market Share To The BOM 
df['Market Share'] = df['Distributor']
df['Market Share'] = df['Distributor'].map(dist_share_dict)
df.head(10)

# RENOTE: Add The Market Share For Alternative Spellings (Twentith Centrury / 20th Century ) at a later stage

,Rank,Release,Genre,Budget,Running Time,Gross,Theaters,Total Gross,Release Date,Distributor,Release Year,Market Share
19749,455,Love Goes Public,-,-,-,$38,-,"$5,738",Oct 25,Aspiration Entertainment,2020,NaN
19748,454,Benjamin the Elephant (2020),-,-,-,$49,1,$49,Oct 16,Viva Pictures,2020,NaN
19747,453,Shooting the Mafia,-,-,-,$88,3,"$10,881",Nov 22,Cohen Media Group,2020,0.01%
19746,452,Chained for Life,-,-,-,$115,3,"$17,431",Sep 13,Kino International,2020,0.01%
19745,451,Asako I & II,-,-,-,$231,3,"$25,559",May 17,Grasshopper Film,2020,0.00%
19744,450,It's for Your Own Good,-,-,-,$256,1,$256,Nov 27,Distrib Films,2020,0.00%
19743,449,The Load,-,-,-,$292,2,"$28,410",Aug 30,Grasshopper Film,2020,0.00%
19742,448,I Do Not Care If We Go Down in History as Barb...,-,-,-,$293,2,"$11,307",Jul 19,Big World Pictures,2020,0.00%
19741,447,Sol,-,-,-,$327,1,$327,Nov 20,Distrib Films,2020,0.00%
19740,446,Island of Lemurs: Madagascar,-,-,-,$374,302,"$11,272,213",Apr 4,Warner Bros.,2020,15.21%